exclude: \.ipynb$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black --target-version py311
        language: system
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q tests
        language: system
        pass_filenames: false
