pipeline: video
metadata_source:
  type: db
  db:
    driver: postgresql+psycopg2
    user: null
    password: null
    host: null
    port: null
    database: null
  tables:
    video_meta: null
    hids_all: null
video_meta_columns:
  - hutom id
  - patient id
  - rawdata_filepath
  - rawdata_filename
  - sourcedata_filepath
  - sourcedata_filename
  - size(bytes)
  - hash
  - width
  - height
  - codec_name
  - fps
  - nb_frames
  - duration
n_digits: 4
run_anonymization: true
recodec: true
verbose: true
datasets:
  - video_dir: /nas/nas6/DataTeam/COLON/[범부처전주기] 민병소교수님/211014_LAR
    center: 범부처전주기
    importdate: "20260413"
    organ: COLON
